# Generated by Django 4.1.7 on 2023-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField()),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('uniquewardid', models.IntegerField()),
                ('polling_unit_number', models.CharField(max_length=50)),
                ('polling_unit_name', models.CharField(max_length=50)),
                ('polling_unit_description', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=15)),
                ('long', models.CharField(max_length=15)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'polling_unit',
            },
        ),
    ]
