# Generated by Django 4.1.7 on 2023-03-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollingUnit',
            new_name='PollingUnits',
        ),
    ]
