# Generated by Django 4.1.7 on 2023-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_pollingunit_pollingunits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('lga_name', models.CharField(max_length=50)),
                ('lga_description', models.CharField(max_length=255)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'lga',
            },
        ),
    ]
